# Generated by Django 4.2.15 on 2026-03-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PendingCheckout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basket_id", models.PositiveIntegerField(unique=True)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("reference", models.CharField(max_length=64)),
                (
                    "shipping_method_code",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("donation", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pending Checkout",
                "verbose_name_plural": "Pending Checkouts",
            },
        ),
    ]
