# Generated by Django 4.2.15 on 2026-04-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingcheckout",
            name="basket_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Frozen basket contents and total at time of checkout.",
            ),
        ),
    ]
