# Generated by Django 4.2.15 on 2026-04-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_add_basket_snapshot_to_pendingcheckout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingcheckout",
            name="basket_id",
            field=models.PositiveIntegerField(),
        ),
    ]
