# Generated by Django 4.2.15 on 2026-04-12 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_remove_basket_id_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnmatchedPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Unmatched Payment",
                "verbose_name_plural": "Unmatched Payments",
            },
        ),
        migrations.AddConstraint(
            model_name="unmatchedpayment",
            constraint=models.UniqueConstraint(
                fields=("order_number", "amount"),
                name="checkout_unmatched_payment_order_amount_uniq",
            ),
        ),
    ]
