"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.conf.locale.en import formats as en_formats
from django.core.exceptions import DisallowedHost
from oscar.defaults import *

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent
PROJECT_DIR = Path(__file__).resolve().parent.parent


def traces_sampler(sampling_context):
    """Sets sampling rate for Sentry logging"""
    wsgi_environ = sampling_context.get("wsgi_environ")
    if wsgi_environ:
        path = wsgi_environ["PATH_INFO"]
        if "dashboard" in path:
            return 0.5
        if "checkout" in path:
            return 1
    return 0.02


def before_send(event, hint):
    """Runs before sending events to Sentry"""
    if "exc_info" in hint:
        exc_type, exc_value, tb = hint["exc_info"]
        if isinstance(exc_value, (DisallowedHost,)):
            return None
    return event


en_formats.DATE_FORMAT = "d M Y"

with open(os.path.join(BASE_DIR, "secrets/db_user.txt")) as f:
    DB_USER = f.read().strip()

with open(os.path.join(BASE_DIR, "secrets/db_pass.txt")) as f:
    DB_PASS = f.read().strip()

with open(os.path.join(BASE_DIR, "secrets/mailersend_key.txt")) as f:
    MAILERSEND_KEY = f.read().strip()

with open(os.path.join(BASE_DIR, "secrets/environment.txt")) as f:
    SESSION_ENVIRONMENT_PRODUCTION = False if f.read().strip() == "False" else True
    TESTING = sys.argv[1:2] == ["test"]
    MIGRATING = sys.argv[1:2] == ["makemigrations"] or sys.argv[1:2] == ["migrate"]
    SESSION_MOD_WSGI = sys.argv[0] == "mod_wsgi"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
with open(os.path.join(BASE_DIR, "secrets/secret_key.txt")) as f:
    SECRET_KEY = f.read().strip()

DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "shop.birdsociety.sg",
]

if SESSION_ENVIRONMENT_PRODUCTION and not TESTING:
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn="https://4b93b14e81bc4b4ebdbfa79be9ac9e78@o1066695.ingest.sentry.io/6059605",
        integrations=[RedisIntegration(), DjangoIntegration()],
        send_default_pii=True,
        before_send=before_send,
        release="birdsoc-public@1.0",
        environment="production" if SESSION_ENVIRONMENT_PRODUCTION else "development",
        traces_sampler=traces_sampler,
        profiles_sample_rate=0.05,
    )
    DEBUG = False

# Application definition

INSTALLED_APPS = [
    "maintenance_mode",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.flatpages",
    "anymail",
    "oscar.config.Shop",
    "apps.order.apps.OrderConfig",
    "apps.shipping.apps.ShippingConfig",
    "apps.catalogue.apps.CatalogueConfig",
    "apps.checkout.apps.CheckoutConfig",
    "apps.customer.apps.CustomerConfig",
    "apps.payment.apps.PaymentConfig",
    "apps.util.apps.UtilConfig",  # added
    "oscar.apps.dashboard.orders.apps.OrdersDashboardConfig",
    "oscar.apps.analytics.apps.AnalyticsConfig",
    "oscar.apps.address.apps.AddressConfig",
    "oscar.apps.catalogue.reviews.apps.CatalogueReviewsConfig",
    "oscar.apps.communication.apps.CommunicationConfig",
    "oscar.apps.partner.apps.PartnerConfig",
    "oscar.apps.basket.apps.BasketConfig",
    "oscar.apps.offer.apps.OfferConfig",
    "oscar.apps.search.apps.SearchConfig",
    "oscar.apps.voucher.apps.VoucherConfig",
    "oscar.apps.wishlists.apps.WishlistsConfig",
    "oscar.apps.dashboard.apps.DashboardConfig",
    "oscar.apps.dashboard.reports.apps.ReportsDashboardConfig",
    "oscar.apps.dashboard.users.apps.UsersDashboardConfig",
    "oscar.apps.dashboard.catalogue.apps.CatalogueDashboardConfig",
    "oscar.apps.dashboard.offers.apps.OffersDashboardConfig",
    "oscar.apps.dashboard.partners.apps.PartnersDashboardConfig",
    "oscar.apps.dashboard.pages.apps.PagesDashboardConfig",
    "oscar.apps.dashboard.ranges.apps.RangesDashboardConfig",
    "oscar.apps.dashboard.reviews.apps.ReviewsDashboardConfig",
    "oscar.apps.dashboard.vouchers.apps.VouchersDashboardConfig",
    "oscar.apps.dashboard.communications.apps.CommunicationsDashboardConfig",
    "oscar.apps.dashboard.shipping.apps.ShippingDashboardConfig",
    # 3rd-party apps that oscar depends on
    "widget_tweaks",
    "haystack",
    "treebeard",
    "sorl.thumbnail",  # Default thumbnail backend, can be replaced
    "django_tables2",
]

FILE_UPLOAD_PERMISSIONS = 0o666

ANYMAIL = {
    # (exact settings here depend on your ESP...)
    "MAILERSEND_API_TOKEN": MAILERSEND_KEY,
    "MAILERSEND_SENDER_DOMAIN": "birdsociety.sg",  # your MailerSend domain, if needed
}

EMAIL_BACKEND = "anymail.backends.mailersend.EmailBackend"
DEFAULT_FROM_EMAIL = "shop@birdsociety.sg"  # if you don't already have this in settings
OSCAR_FROM_EMAIL = DEFAULT_FROM_EMAIL
SERVER_EMAIL = (
    "shop-server@birdsociety.sg"  # ditto (default from-email for Django errors)
)

SITE_ID = 1

MAINTENANCE_MODE = None
SESSION_COOKIE_NAME = "dev"

if SESSION_ENVIRONMENT_PRODUCTION and not TESTING:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_NAME = "prod"

SECURE_HSTS_SECONDS = 30
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "maintenance_mode.middleware.MaintenanceModeMiddleware",
    "oscar.apps.basket.middleware.BasketMiddleware",
    "django.contrib.flatpages.middleware.FlatpageFallbackMiddleware",
]


LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "filters": {
        "require_not_maintenance_mode_503": {
            "()": "maintenance_mode.logging.RequireNotMaintenanceMode503",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "formatters": {
        "django.server": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[{server_time}] {message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "filters": ["require_debug_true"],
        },
        "django.server": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "django.server",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "filters": ["require_not_maintenance_mode_503", "require_debug_false"],
            "include_html": True,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "django.server": {
            "handlers": ["django.server"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

if not SESSION_ENVIRONMENT_PRODUCTION and not TESTING:
    MIDDLEWARE.insert(6, "debug_toolbar.middleware.DebugToolbarMiddleware")
    INSTALLED_APPS.append("debug_toolbar")
    os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
    DEBUG_TOOLBAR_CONFIG = {
        "RESULTS_CACHE_SIZE": 100,
    }

elif SESSION_ENVIRONMENT_PRODUCTION:
    MIDDLEWARE.insert(9, "active_users.middleware.ActiveUsersSessionMiddleware")
    LOGGING["loggers"]["django"]["handlers"].append("mail_admins")
    INSTALLED_APPS.append("django.contrib.staticfiles")

if SESSION_ENVIRONMENT_PRODUCTION:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://127.0.0.1:6379/4",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "TIMEOUT": 300,  # Default cache timeout
        },
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        },
        "actions": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        },
    }

OSCAR_HIDDEN_FEATURES = ["reviews", "wishlists", "offers"]

AUTHENTICATION_BACKENDS = (
    "oscar.apps.customer.auth_backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
)

ADMINS = [("Raghav Narayanswamy", "raghavnswamy@gmail.com")]

ADMIN_EMAILS = [i[1] for i in ADMINS]

HAYSTACK_CONNECTIONS = {
    "default": {
        "ENGINE": "haystack.backends.simple_backend.SimpleEngine",
    },
}

ROOT_URLCONF = "shop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(PROJECT_DIR, "shop/templates")],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "oscar.apps.search.context_processors.search_form",
                "oscar.apps.checkout.context_processors.checkout",
                "oscar.apps.communication.notifications.context_processors.notifications",
                "oscar.core.context_processors.metadata",
            ],
            "loaders": [
                (
                    "django.template.loaders.cached.Loader",
                    [
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                    ],
                ),
                "django.template.loaders.app_directories.Loader",
            ],
        },
    },
]

WSGI_APPLICATION = "shop.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Singapore"

USE_I18N = True

USE_TZ = True

db_defaults = {
    "ENGINE": "django.db.backends.postgresql",
    "NAME": "shop",
    "USER": DB_USER,
    "PASSWORD": DB_PASS,
    "HOST": "127.0.0.1",
    "PORT": 5432,
}

if SESSION_ENVIRONMENT_PRODUCTION:
    db_defaults["CONN_MAX_AGE"] = 90

DATABASES = {
    "default": db_defaults,
}

OSCAR_DEFAULT_CURRENCY = "SGD"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

if SESSION_ENVIRONMENT_PRODUCTION:
    STATIC_ROOT = os.path.join(PROJECT_DIR, "static/")
else:
    STATICFILES_DIRS = ("static/",)

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_ROOT = os.path.join(PROJECT_DIR, "media/")
MEDIA_URL = "media/"

OSCAR_CURRENCY_FORMAT = {
    "SGD": {
        "format": "$#,##0.00",
    }
}

OSCAR_SHOP_NAME = "BirdSoc SG Shop"

GLOBAL_SELF_COLLECTION_REQUIRED = True
GLOBAL_PAYNOW_REQUIRED = True
BASE_ORDER_NUMBER = 128967
CONTACT_US_URL = "https://birdsociety.sg/contact-us/"

PAYMENT_CONFIRMED_STATUS = "Payment confirmed"
CANCELLED_STATUS = "Cancelled"
COLLECTED_STATUS = "Collected"
SHIPPED_STATUS = "Shipped"

OSCAR_INITIAL_ORDER_STATUS = "Pending"
OSCAR_INITIAL_LINE_STATUS = "Pending"
OSCAR_ORDER_STATUS_PIPELINE = {
    "Pending": (
        PAYMENT_CONFIRMED_STATUS,
        CANCELLED_STATUS,
    ),
    "Payment confirmed": (
        COLLECTED_STATUS,
        CANCELLED_STATUS,
    ),
    "Cancelled": (),
}
