"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.conf.locale.en import formats as en_formats
from django.core.exceptions import DisallowedHost
from oscar.defaults import *

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

from django.utils.translation import gettext_lazy as _

# Import dotenv for .env file support
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent
PROJECT_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(PROJECT_DIR, ".env"))


def traces_sampler(sampling_context):
    """Sets sampling rate for Sentry logging"""
    wsgi_environ = sampling_context.get("wsgi_environ")
    if wsgi_environ:
        path = wsgi_environ["PATH_INFO"]
        if "dashboard" in path:
            return 0.5
        if "checkout" in path:
            return 1
    return 0.02


def before_send(event, hint):
    """Runs before sending events to Sentry"""
    if "exc_info" in hint:
        exc_type, exc_value, tb = hint["exc_info"]
        if isinstance(exc_value, (DisallowedHost,)):
            return None
    return event


en_formats.DATE_FORMAT = "d M Y"

# Get database credentials from environment variables with fallback to files
DB_USER = os.environ.get("DB_USER", "")
DB_PASS = os.environ.get("DB_PASS", "")
MAILERSEND_KEY = os.environ.get("MAILERSEND_KEY", "")
SESSION_ENVIRONMENT_PRODUCTION = os.environ.get("ENVIRONMENT", "False") == "True"

SALES_EMAIL = os.environ.get("SALES_EMAIL", "")

SHOP_OPEN = True
SHOP_OPEN_PUBLIC = True
TESTING = sys.argv[1:2] == ["test"]

SHOP_OPEN = TESTING or SHOP_OPEN or not SESSION_ENVIRONMENT_PRODUCTION

TESTING = sys.argv[1:2] == ["test"]
MIGRATING = sys.argv[1:2] == ["makemigrations"] or sys.argv[1:2] == ["migrate"]
SESSION_MOD_WSGI = sys.argv[0] == "mod_wsgi"

# Get secret key
SECRET_KEY = os.environ.get("SECRET_KEY", "")

WHITELIST_USERS = []
if os.path.exists(os.path.join(PROJECT_DIR, "config/whitelist.txt")):
    with open(os.path.join(PROJECT_DIR, "config/whitelist.txt")) as f:
        WHITELIST_USERS = [e.strip() for e in f.read().strip().splitlines()]

JWT_SECRET = os.environ.get("JWT_SECRET", "")

# Gmail API credentials for PayNow polling (optional feature)
GMAIL_CLIENT_ID = os.environ.get("GMAIL_CLIENT_ID", "")
GMAIL_CLIENT_SECRET = os.environ.get("GMAIL_CLIENT_SECRET", "")
GMAIL_REFRESH_TOKEN = os.environ.get("GMAIL_REFRESH_TOKEN", "")
GMAIL_TEST_RECIPIENT = os.environ.get("GMAIL_TEST_RECIPIENT", "")
GMAIL_ALLOWED_FROM_ADDRESSES = os.environ.get("GMAIL_ALLOWED_FROM_ADDRESSES", "")
GMAIL_ALLOWED_FROM_DOMAINS = os.environ.get("GMAIL_ALLOWED_FROM_DOMAINS", "")
# Gmail search query used to find PayNow notifications
GMAIL_POLL_QUERY = os.environ.get(
    "GMAIL_POLL_QUERY",
    'subject:"PayNow Alert - You have received a payment via PayNow" newer_than:1d',
)
# Maximum age for messages to consider (minutes)
GMAIL_MAX_AGE_MINUTES = int(os.environ.get("GMAIL_MAX_AGE_MINUTES", "60"))

AUTH0_DOMAIN = os.environ.get("AUTH0_DOMAIN")
AUTH0_CLIENT_ID = os.environ.get("AUTH0_CLIENT_ID")
AUTH0_CLIENT_SECRET = os.environ.get("AUTH0_CLIENT_SECRET")

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "shop.birdsociety.sg",
]

if not SESSION_ENVIRONMENT_PRODUCTION:
    ALLOWED_HOSTS += [".ngrok-free.app"]

OSCAR_STATIC_BASE_URL = "https://shop.birdsociety.sg/"
SOCIETY_HOME_PAGE = "https://birdsociety.sg/"

DEBUG = True

if SESSION_ENVIRONMENT_PRODUCTION and not TESTING:
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn=os.environ.get("SENTRY_DSN"),
        integrations=[RedisIntegration(), DjangoIntegration()],
        send_default_pii=True,
        before_send=before_send,
        release="birdsoc-public@1.0",
        environment="production" if SESSION_ENVIRONMENT_PRODUCTION else "development",
        traces_sampler=traces_sampler,
        profiles_sample_rate=0.05,
    )
    DEBUG = False

# Application definition

INSTALLED_APPS = [
    "maintenance_mode",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.humanize",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.flatpages",
    "anymail",
    "rest_framework",
    "oscar.config.Shop",
    "apps.order.apps.OrderConfig",
    "apps.shipping.apps.ShippingConfig",
    "apps.dashboard.shipping.apps.ShippingDashboardConfig",
    "apps.catalogue.apps.CatalogueConfig",
    "apps.checkout.apps.CheckoutConfig",
    "apps.customer.apps.CustomerConfig",
    "apps.payment.apps.PaymentConfig",
    "apps.offer.apps.OfferConfig",
    "apps.util.apps.UtilConfig",  # added
    "apps.api.apps.ApiConfig",
    "apps.home.apps.MyShop",
    "apps.communication.apps.CommunicationConfig",
    "apps.refund.apps.RefundConfig",  # Add the new refund app
    "apps.dashboard.refund.apps.RefundDashboardConfig",  # Add the new refund app
    "apps.dashboard.catalogue.apps.CatalogueDashboardConfig",
    "apps.event.apps.EventConfig",  # Add the new events app
    "apps.dashboard.event.apps.EventDashboardConfig",  # Event dashboard app - Add this line
    "apps.form.apps.FormConfig",  # Dynamic forms app
    "apps.dashboard.form.apps.FormDashboardConfig",  # Forms dashboard
    "apps.faq.apps.FAQConfig",
    "apps.dashboard.faq.apps.FAQDashboardConfig",
    "apps.banner.apps.BannerConfig",
    "apps.dashboard.banner.apps.BannerDashboardConfig",
    "oscar.apps.dashboard.users.apps.UsersDashboardConfig",
    "apps.dashboard.orders.apps.OrdersDashboardConfig",
    "oscar.apps.analytics.apps.AnalyticsConfig",
    "oscar.apps.address.apps.AddressConfig",
    "oscar.apps.catalogue.reviews.apps.CatalogueReviewsConfig",
    "apps.partner.apps.PartnerConfig",
    "oscar.apps.basket.apps.BasketConfig",
    "oscar.apps.search.apps.SearchConfig",
    "oscar.apps.voucher.apps.VoucherConfig",
    "oscar.apps.wishlists.apps.WishlistsConfig",
    "oscar.apps.dashboard.apps.DashboardConfig",
    "oscar.apps.dashboard.reports.apps.ReportsDashboardConfig",
    "oscar.apps.dashboard.offers.apps.OffersDashboardConfig",
    "oscar.apps.dashboard.partners.apps.PartnersDashboardConfig",
    "oscar.apps.dashboard.pages.apps.PagesDashboardConfig",
    "oscar.apps.dashboard.ranges.apps.RangesDashboardConfig",
    "oscar.apps.dashboard.reviews.apps.ReviewsDashboardConfig",
    "oscar.apps.dashboard.vouchers.apps.VouchersDashboardConfig",
    "oscar.apps.dashboard.communications.apps.CommunicationsDashboardConfig",
    # 3rd-party apps that oscar depends on
    "widget_tweaks",
    "haystack",
    "treebeard",
    "django_tables2",
    "django_contact_form",
    "crispy_forms",
    "crispy_bootstrap4",
    "sorl.thumbnail",
]

FILE_UPLOAD_PERMISSIONS = 0o666

ANYMAIL = {
    "MAILERSEND_API_TOKEN": MAILERSEND_KEY,
    "MAILERSEND_SENDER_DOMAIN": os.environ.get("MAILERSEND_SENDER_DOMAIN"), 
}

EMAIL_BACKEND = "anymail.backends.mailersend.EmailBackend"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")
OSCAR_FROM_EMAIL = DEFAULT_FROM_EMAIL
REPLY_TO_EMAIL = os.environ.get("REPLY_TO_EMAIL")
SERVER_EMAIL = os.environ.get("SERVER_EMAIL")

SITE_ID = 1

MAINTENANCE_MODE = None
SESSION_COOKIE_NAME = "dev"

if SESSION_ENVIRONMENT_PRODUCTION and not TESTING:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_NAME = "prod"

SECURE_HSTS_SECONDS = 30
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "maintenance_mode.middleware.MaintenanceModeMiddleware",
    "oscar.apps.basket.middleware.BasketMiddleware",
    "django.contrib.flatpages.middleware.FlatpageFallbackMiddleware",
    "apps.util.middleware.NoAdminMiddleware",
]

if not SHOP_OPEN:
    MIDDLEWARE.append("apps.util.middleware.LoginRequiredMiddleware")

INTERNAL_IPS = [
    "127.0.0.1",
]


LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "filters": {
        "require_not_maintenance_mode_503": {
            "()": "maintenance_mode.logging.RequireNotMaintenanceMode503",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "formatters": {
        "django.server": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[{server_time}] {message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "filters": ["require_debug_true"],
        },
        "django.server": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "django.server",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "filters": ["require_not_maintenance_mode_503", "require_debug_false"],
            "include_html": True,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "django.server": {
            "handlers": ["django.server"],
            "level": "INFO",
            "propagate": False,
        },
        "oscar.checkout": {
            "level": "INFO",
            "handlers": ["console"],
        },
    },
}

if not SESSION_ENVIRONMENT_PRODUCTION and not TESTING:
    MIDDLEWARE.insert(6, "debug_toolbar.middleware.DebugToolbarMiddleware")
    INSTALLED_APPS.append("debug_toolbar")
    os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
    DEBUG_TOOLBAR_CONFIG = {
        "RESULTS_CACHE_SIZE": 100,
        "SHOW_TOOLBAR_CALLBACK": "apps.util.middleware.show_debug_toolbar",
    }

elif SESSION_ENVIRONMENT_PRODUCTION:
    LOGGING["loggers"]["django"]["handlers"].append("mail_admins")

if SESSION_ENVIRONMENT_PRODUCTION:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://127.0.0.1:6379/4",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "TIMEOUT": 300,  # Default cache timeout
        },
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        },
        "actions": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        },
    }

# Ensure tests never depend on Redis
if TESTING:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        },
        "actions": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        },
    }


db_defaults = {
    "ENGINE": "django.db.backends.postgresql",
    "NAME": "shop_backup",
    "USER": DB_USER,
    "PASSWORD": DB_PASS,
    "HOST": "127.0.0.1",
    "PORT": 5432,
}

if SESSION_ENVIRONMENT_PRODUCTION:
    db_defaults["CONN_MAX_AGE"] = 90

# Use SQLite for tests to simplify local execution without Postgres
if TESTING:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(PROJECT_DIR, "dev_db.sqlite3"),
            "TEST": {
                "NAME": os.path.join(PROJECT_DIR, "test_db.sqlite3"),
            },
        }
    }
else:
    DATABASES = {
        "default": db_defaults,
    }

OSCAR_HIDDEN_FEATURES = ["reviews", "wishlists", "offers"]
OSCAR_SEND_REGISTRATION_EMAIL = False

AUTHENTICATION_BACKENDS = (
    "oscar.apps.customer.auth_backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
)

ADMIN_NAME = os.environ.get("ADMIN_NAME")
ADMIN_EMAIL = os.environ.get("ADMIN_EMAIL")
ADMINS = [(ADMIN_NAME, ADMIN_EMAIL)]
MANAGERS = [
    ("BirdSoc SG Outreach", os.environ.get("OUTREACH_EMAIL")),
    ("BirdSoc SG Sales", os.environ.get("SALES_EMAIL")),
]
MANAGER_EMAILS = [i[1] for i in MANAGERS]
ADMIN_EMAILS = [i[1] for i in ADMINS]
TREASURER_EMAIL = os.environ.get("TREASURER_EMAIL")

if not SESSION_ENVIRONMENT_PRODUCTION:  # test config
    MANAGER_EMAILS = ADMIN_EMAILS
    TREASURER_EMAIL = ADMIN_EMAIL

HAYSTACK_CONNECTIONS = {
    "default": {
        "ENGINE": "haystack.backends.simple_backend.SimpleEngine",
    },
}

ROOT_URLCONF = "shop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(PROJECT_DIR, "shop/templates")],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "oscar.apps.search.context_processors.search_form",
                "oscar.apps.checkout.context_processors.checkout",
                "oscar.apps.communication.notifications.context_processors.notifications",
                "oscar.core.context_processors.metadata",
                "apps.util.context_processors.whitelist",
            ],
            "loaders": [
                (
                    "django.template.loaders.cached.Loader",
                    [
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                    ],
                ),
                "django.template.loaders.app_directories.Loader",
            ],
        },
    },
]

WSGI_APPLICATION = "shop.wsgi.application"

# REST framework configuration
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
    "DEFAULT_PAGINATION_CLASS": "apps.api.pagination.DefaultPagination",
    "PAGE_SIZE": 20,
}

# CORS configuration
CORS_ALLOW_CREDENTIALS = False
# Adjust this in production
CORS_ALLOW_ALL_ORIGINS = not SESSION_ENVIRONMENT_PRODUCTION

CORS_ALLOWED_ORIGIN_REGEXES = ["https:\/\/([a-z0-9-]+\.)*birdsociety\.sg$"]

# Allow API URLs to bypass login-required middleware
OPEN_URLS = [
    "/api/",
]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_HASHERS = [
    "shop.hashers.MinArgon2PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Singapore"

USE_I18N = True

USE_TZ = True

OSCAR_DEFAULT_CURRENCY = "SGD"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

if SESSION_ENVIRONMENT_PRODUCTION:
    STATIC_ROOT = os.path.join(PROJECT_DIR, "static/")
else:
    STATICFILES_DIRS = ("static/",)

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MIGRATION_MODULES = {
    "partner": "apps.partner.migrations",
}

MEDIA_ROOT = os.path.join(PROJECT_DIR, "media/")
MEDIA_URL = "media/"

OSCAR_CURRENCY_FORMAT = {
    "SGD": {
        "format": "$#,##0.00",
    }
}

OSCAR_SHOP_NAME = "BirdSoc SG Shop"

GLOBAL_SELF_COLLECTION_REQUIRED = True
GLOBAL_PAYNOW_REQUIRED = True
BASE_ORDER_NUMBER = 100000
BASE_ORDER_NUMBER_ONSITE = 200000
CONTACT_US_URL = "https://shop.birdsociety.sg/contact/"

PAYMENT_CONFIRMED_STATUS = "Payment confirmed"
PAYMENT_AUTO_CONFIRMED_STATUS = "Payment automatically confirmed"
CANCELLED_STATUS = "Cancelled"
COLLECTED_STATUS = "Collected"
COLLECTION_INFO_SENT_STATUS = "Collection info sent"
SHIPPED_STATUS = "Shipped"

OSCAR_INITIAL_ORDER_STATUS = "Pending payment confirmation"
OSCAR_INITIAL_LINE_STATUS = "Pending payment confirmation"
OSCAR_ORDER_STATUS_PIPELINE = {
    OSCAR_INITIAL_ORDER_STATUS: (
        PAYMENT_CONFIRMED_STATUS,
        PAYMENT_AUTO_CONFIRMED_STATUS,
        CANCELLED_STATUS,
    ),
    PAYMENT_CONFIRMED_STATUS: (
        COLLECTION_INFO_SENT_STATUS,
        COLLECTED_STATUS,
        CANCELLED_STATUS,
    ),
    PAYMENT_AUTO_CONFIRMED_STATUS: (
        COLLECTION_INFO_SENT_STATUS,
        COLLECTED_STATUS,
        CANCELLED_STATUS,
    ),
    COLLECTION_INFO_SENT_STATUS: (COLLECTED_STATUS, CANCELLED_STATUS),
    COLLECTED_STATUS: (PAYMENT_AUTO_CONFIRMED_STATUS,),
    CANCELLED_STATUS: (),
}
ORDER_LINE_STATUS_PIPELINE = OSCAR_ORDER_STATUS_PIPELINE
OSCAR_ORDER_STATUS_CASCADE = {
    OSCAR_INITIAL_ORDER_STATUS: OSCAR_INITIAL_LINE_STATUS,
    PAYMENT_CONFIRMED_STATUS: PAYMENT_CONFIRMED_STATUS,
    CANCELLED_STATUS: CANCELLED_STATUS,
    COLLECTION_INFO_SENT_STATUS: COLLECTION_INFO_SENT_STATUS,
    COLLECTED_STATUS: COLLECTED_STATUS,
}

OSCAR_DASHBOARD_NAVIGATION = [
    {
        "label": _("Dashboard"),
        "icon": "fas fa-list",
        "url_name": "dashboard:index",
    },
    {
        "label": _("Catalogue"),
        "icon": "fas fa-sitemap",
        "children": [
            {
                "label": _("Products"),
                "url_name": "dashboard:catalogue-product-list",
            },
            {
                "label": _("Product Types"),
                "url_name": "dashboard:catalogue-class-list",
            },
            {
                "label": _("Categories"),
                "url_name": "dashboard:catalogue-category-list",
            },
            {
                "label": _("Ranges"),
                "url_name": "dashboard:range-list",
            },
            {
                "label": _("Cost Prices"),
                "url_name": "dashboard:catalogue-cost-prices",
            },
            # {
            #     "label": _("Low stock alerts"),
            #     "url_name": "dashboard:stock-alert-list",
            # },
            # {
            #     "label": _("Options"),
            #     "url_name": "dashboard:catalogue-option-list",
            # },
            # {
            #     "label": _("Attribute Option Groups"),
            #     "url_name": "dashboard:catalogue-attribute-option-group-list",
            # },
        ],
    },
    {
        "label": _("Fulfilment"),
        "icon": "fas fa-shopping-cart",
        "children": [
            {
                "label": _("Orders"),
                "url_name": "dashboard:order-list",
            },
            {
                "label": _("Statistics"),
                "url_name": "dashboard:order-stats",
            },
            {
                "label": _("Onsite purchases"),
                "url_name": "dashboard:onsite-purchase",
            },
            {
                "label": _("Sales Report"),
                "url_name": "dashboard:sales-report",
            },
            {
                "label": _("Pending Checkouts"),
                "url_name": "dashboard:pending-checkouts",
                "access_fn": lambda user, _url_name, _url_args, _url_kwargs: user.is_superuser,
            },
        ],
    },
    {
        "label": _("Customers"),
        "icon": "fas fa-users",
        "children": [
            {
                "label": _("Customers"),
                "url_name": "dashboard:users-index",
            },
            # {
            #     "label": _("Stock alert requests"),
            #     "url_name": "dashboard:user-alert-list",
            # },
        ],
        "access_fn": lambda user, _url_name, _url_args, _url_kwargs: user.is_superuser,
    },
    {
        "label": "Shipping",
        "icon": "fa fa-truck",
        "children": [
            {
                "label": _("Methods"),
                "url_name": "dashboard:dynamic-shipping-method-list",
            },
        ],
        "access_fn": lambda user, _url_name, _url_args, _url_kwargs: user.is_superuser,
    },
    {
        "label": _("Offers"),
        "icon": "fas fa-bullhorn",
        "children": [
            {
                "label": _("Offers"),
                "url_name": "dashboard:offer-list",
            },
            {
                "label": _("Vouchers"),
                "url_name": "dashboard:voucher-list",
            },
            {
                "label": _("Voucher Sets"),
                "url_name": "dashboard:voucher-set-list",
            },
        ],
    },
    # {
    #     "label": _("Content"),
    #     "icon": "fas fa-folder",
    #     "children": [
    #         {
    #             "label": _("Pages"),
    #             "url_name": "dashboard:page-list",
    #         },
    #         {
    #             "label": _("Email templates"),
    #             "url_name": "dashboard:comms-list",
    #         },
    #         {
    #             "label": _("Reviews"),
    #             "url_name": "dashboard:reviews-list",
    #         },
    #     ],
    # },
    {
        "label": _("Reports"),
        "icon": "fas fa-chart-bar",
        "url_name": "dashboard:reports-index",
        "access_fn": lambda user, _url_name, _url_args, _url_kwargs: user.is_superuser,
    },
    {
        "label": _("Events"),
        "icon": "fas fa-calendar-alt",
        "children": [
            {
                "label": _("Events"),
                "url_name": "dashboard-event:event-list",
                "access_fn": lambda user,
                _url_name,
                _url_args,
                _url_kwargs: user.is_staff,
            },
            {
                "label": _("Participants"),
                "url_name": "dashboard-event:participant-list",
                "access_fn": lambda user,
                _url_name,
                _url_args,
                _url_kwargs: user.is_staff,
            },
        ],
    },
    {
        "label": _("FAQ"),
        "icon": "fas fa-question-circle",
        "url_name": "dashboard-faq:faq-list",
        "access_fn": lambda user, _url_name, _url_args, _url_kwargs: user.is_staff,
    },
    {
        "label": _("Refunds"),
        "icon": "fas fa-hand-holding-usd",
        "url_name": "dashboard-refund:refund-request-list",
        "access_fn": lambda user, _url_name, _url_args, _url_kwargs: user.is_superuser,
    },
    {
        "label": _("Forms"),
        "icon": "fas fa-clipboard-list",
        "url_name": "dashboard-form:form-list",
        "access_fn": lambda user, _url_name, _url_args, _url_kwargs: user.is_staff,
    },
    {
        "label": _("Banner"),
        "icon": "fas fa-image",
        "children": [
            {
                "label": _("Text"),
                "url_name": "dashboard-banner:banner-text",
                "access_fn": lambda user, _url_name, _url_args, _url_kwargs: user.is_staff,
            },
            {
                "label": _("Images"),
                "url_name": "dashboard-banner:banner-list",
                "access_fn": lambda user, _url_name, _url_args, _url_kwargs: user.is_staff,
            },
        ],
        "access_fn": lambda user, _url_name, _url_args, _url_kwargs: user.is_staff,
    },
]

ORDER_PREFIX = "MER-"
CRISPY_TEMPLATE_PACK = "bootstrap4"

OSCAR_GOOGLE_ANALYTICS_ID = "G-8Z3R0WMMV7"

LOGIN_ONLY_URL = "/accounts/login-only/"
LOGIN_REDIRECT_URL = "/"

if SESSION_ENVIRONMENT_PRODUCTION:
    OSCAR_THUMBNAILER = "core.thumbnailer.LargeSorlThumbnail"
else:
    OSCAR_THUMBNAILER = "core.thumbnailer.FakeThumbnail"

OSCAR_HOMEPAGE = "/"
OSCAR_SHIPPING_REPOSITORY = "apps.shipping.Repository"
