# Generated by Django 4.2.15 on 2025-03-14 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_participant_quantity"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="participant",
            name="unique_participant_email",
        ),
    ]
