# Generated by Django 4.2 on 2025-03-14
from django.db import migrations


def confirm_existing_eventparticipants(apps, schema_editor):
    EventParticipant = apps.get_model("event", "EventParticipant")
    EventParticipant.objects.update(is_confirmed=True)


def noop_reverse(apps, schema_editor):
    # Intentionally do nothing on reverse; we don't want to unset confirmations
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_paid_event_fields"),
    ]

    operations = [
        migrations.RunPython(confirm_existing_eventparticipants, noop_reverse),
    ]
