# Generated by Django 4.2.15 on 2025-08-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_confirm_existing_eventparticipants"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipant",
            name="extra_json",
            field=models.JSONField(blank=True, null=True, verbose_name="Extra data"),
        ),
        migrations.AddField(
            model_name="organizedevent",
            name="json_schema",
            field=models.CharField(
                blank=True,
                help_text="Optional JSON schema for additional participant data",
                max_length=255,
                null=True,
                verbose_name="JSON schema",
            ),
        ),
        migrations.AddField(
            model_name="organizedevent",
            name="validate_participant_data",
            field=models.BooleanField(
                default=False,
                help_text="If true, participant data will be validated against the JSON schema",
                verbose_name="Validate participant data",
            ),
        ),
    ]
