# Generated by Django 4.2.15 on 2025-08-28

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
import apps.payment.models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0007_alter_json_schema_to_jsonfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRegistrationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payer_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Payer Name"
                    ),
                ),
                (
                    "payer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Payer Email"
                    ),
                ),
                (
                    "payer_phone",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Payer Phone"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending payment"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("amount_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="SGD", max_length=8)),
                ("reference", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payment_verified", models.BooleanField(default=False)),
                ("payment_verified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_proof",
                    models.ImageField(
                        null=True, upload_to=apps.payment.models.get_payment_proof_path
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.organizedevent",
                    ),
                ),
                (
                    "payment_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="event.eventregistrationgroup",
            ),
        ),
    ]
