# Generated by Django 4.2.15 on 2025-09-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0010_add_donation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizedevent",
            name="confirmed_email_template",
            field=models.TextField(
                blank=True,
                help_text="HTML email template sent when payment is confirmed. Available variables: {{first_name}}, {{last_name}}, {{email}}, {{phone_number}}, {{quantity}}, {{event_title}}, {{event_date}}, {{event_location}}, {{amount}}, {{currency}}",
                null=True,
                verbose_name="Payment Confirmation Email Template",
            ),
        ),
    ]
