# Generated by Django 4.2.15 on 2025-09-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0011_add_confirmed_email_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipant",
            name="is_main_contact",
            field=models.BooleanField(
                default=True,
                help_text="Only main contacts receive payment confirmation emails",
                verbose_name="Main Contact",
            ),
        ),
    ]
