# Generated by Django 4.2.15 on 2025-09-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0012_add_is_main_contact_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Emergency Contact Name"
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Emergency Contact Phone"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Emergency Contact Name"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Emergency Contact Phone"
            ),
        ),
        migrations.AlterField(
            model_name="organizedevent",
            name="confirmed_email_template",
            field=models.TextField(
                blank=True,
                help_text="HTML email template sent when payment is confirmed. Available variables: {{first_name}}, {{last_name}}, {{email}}, {{phone_number}}, {{quantity}}, {{event_title}}, {{event_date}}, {{event_location}}, {{amount}}, {{currency}}, {{participant_details}}",
                null=True,
                verbose_name="Payment Confirmation Email Template",
            ),
        ),
    ]
