# Generated by Django 4.2.15 on 2026-04-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0018_add_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
