# Generated by Django 4.2.15 on 2026-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0019_alter_eventimage_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizedevent",
            name="post_registration_message",
            field=models.TextField(
                blank=True,
                help_text="Custom message shown on the confirmation page after a participant registers (plain text or simple HTML).",
                null=True,
                verbose_name="Post-registration message",
            ),
        ),
        migrations.AddField(
            model_name="organizedevent",
            name="registration_open",
            field=models.BooleanField(
                default=True,
                help_text="When unchecked, the registration form is closed even if the event is active. Use this to manually pause registrations for a specific event.",
                verbose_name="Registration open",
            ),
        ),
        migrations.AddField(
            model_name="organizedevent",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of tag strings for categorising this event",
                null=True,
                verbose_name="Tags",
            ),
        ),
    ]
