# Generated by Django 4.2.15 on 2026-06-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0026_console_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizedevent",
            name="collect_prior_attendance",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, participants are asked whether they have attended this event before. In lottery mode, returning participants are deprioritized in the draw.",
                verbose_name="Collect prior attendance",
            ),
        ),
    ]
