# Generated by Django 4.2.15 on 2026-06-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0027_collect_prior_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipant",
            name="is_member",
            field=models.BooleanField(default=False, verbose_name="BirdSoc member"),
        ),
    ]
