# Generated by Django 4.2.15 on 2026-06-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0028_ep_is_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizedevent",
            name="lottery_lost_email_subject",
            field=models.CharField(
                blank=True,
                help_text="Subject line for the email sent to participants who weren't selected. Leave blank to use the default. Supports {{first_name}}, {{last_name}}, {{event_title}}, {{event_date}}, {{event_location}}, {{quantity}}.",
                max_length=255,
                null=True,
                verbose_name="Lottery 'not selected' email subject",
            ),
        ),
        migrations.AddField(
            model_name="organizedevent",
            name="lottery_lost_email_template",
            field=models.TextField(
                blank=True,
                help_text="HTML body for the email sent to participants who weren't selected. Leave blank to use the default. Available variables: {{first_name}}, {{last_name}}, {{email}}, {{phone_number}}, {{quantity}}, {{event_title}}, {{event_date}}, {{event_location}}",
                null=True,
                verbose_name="Lottery 'not selected' email body",
            ),
        ),
        migrations.AddField(
            model_name="organizedevent",
            name="lottery_won_email_subject",
            field=models.CharField(
                blank=True,
                help_text="Subject line for the email sent to lottery winners. Leave blank to use the default. Supports {{first_name}}, {{last_name}}, {{event_title}}, {{event_date}}, {{event_location}}, {{quantity}}.",
                max_length=255,
                null=True,
                verbose_name="Lottery 'won' email subject",
            ),
        ),
        migrations.AddField(
            model_name="organizedevent",
            name="lottery_won_email_template",
            field=models.TextField(
                blank=True,
                help_text="HTML body for the email sent to lottery winners. Leave blank to use the default. Available variables: {{first_name}}, {{last_name}}, {{email}}, {{phone_number}}, {{quantity}}, {{event_title}}, {{event_date}}, {{event_location}}",
                null=True,
                verbose_name="Lottery 'won' email body",
            ),
        ),
    ]
