# Generated by Django 4.2.15 on 2026-09-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0031_eventparticipant_lottery_result_email_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizedevent",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Free-form JSON for presentation data that lives with the event (e.g. landing-page site-card fields: order, ebird_url, start, end). Not used by registration or payment logic.",
                null=True,
                verbose_name="Metadata",
            ),
        ),
    ]
