# Generated by Django 4.2.15 on 2026-09-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0032_organizedevent_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier used in group landing links.",
                        max_length=300,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Free-form presentation data shared across the group.",
                        null=True,
                        verbose_name="Metadata",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Event Group",
                "verbose_name_plural": "Event Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EventAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Machine slug for this allocation, e.g. 'nparks'.",
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human label shown to eligible registrants, e.g. 'NParks Volunteer'.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "total_slots",
                    models.PositiveIntegerField(
                        help_text="Size of the reserved pool, shared across the whole group.",
                        verbose_name="Total slots",
                    ),
                ),
                (
                    "price_incl_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Price (incl tax)",
                    ),
                ),
                (
                    "max_qty_per_registration",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Cap on tickets a single registration may book from this pool.",
                        verbose_name="Max quantity per registration",
                    ),
                ),
                (
                    "access_code",
                    models.CharField(
                        blank=True,
                        help_text="Code that unlocks this allocation (matched case-insensitively). Delivered via the group landing link; leave blank to disable the gate.",
                        max_length=64,
                        verbose_name="Access code",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="event.eventgroup",
                        verbose_name="Event Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Allocation",
                "verbose_name_plural": "Event Allocations",
                "ordering": ["group", "name"],
                "unique_together": {("group", "code")},
            },
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="allocation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registrations",
                to="event.eventallocation",
            ),
        ),
        migrations.AddField(
            model_name="organizedevent",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional group tying this event to a wider campaign/series. Enables shared reserved allocations across every event in the group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="event.eventgroup",
                verbose_name="Event Group",
            ),
        ),
    ]
