# Generated by Django 4.2.15 on 2026-09-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0033_event_group_and_allocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizedevent",
            name="collect_driving",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, participants are asked whether they will be driving to the event (Yes / No / Unsure).",
                verbose_name="Collect driving",
            ),
        ),
    ]
