# Generated by Django 4.2.15 on 2026-04-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_open", models.BooleanField(default=True)),
                ("shop_open_public", models.BooleanField(default=True)),
                ("close_datetime", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Shop Configuration",
            },
        ),
    ]
