# Generated by Django 4.2.15 on 2026-03-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0006_auto_20200724_0909"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrecord",
            name="crossed_out_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original price to display crossed out (e.g. before discount).",
                max_digits=12,
                null=True,
            ),
        ),
    ]
