# Generated by Django 4.2.15 on 2026-02-21 07:13

from django.db import migrations


def seed_faq(apps, schema_editor):
    FAQItem = apps.get_model("faq", "FAQItem")

    items = [
        {
            "question": "How do I pay?",
            "answer": "<p>We accept payment via PayNow. Specific payment instructions will be available when you add items to your cart and check out.</p>",
            "position": 0,
        },
        {
            "question": "What will BirdSoc SG do with the proceeds from merchandise sales?",
            "answer": "<p>We are a fully volunteer-run organization. All proceeds from merchandise sales, including donations, will go towards our signature projects, funding our events, and web server expenses for our websites.</p>",
            "position": 1,
        },
        {
            "question": "How do I get my items?",
            "answer": "<p>For this round of merchandise sales, we're collecting orders between now and 22 Mar 2025. This sales round is exclusive for participants at our Bishan-Ang Mo Kio Park walk on 29 Mar 2025. </p>",
            "position": 2,
        },
        {
            "question": "Can I buy the items on site?",
            "answer": "<p>We won't be selling the items physically on site. Sales will be conducted online, and you can collect your items on site.</p>",
            "position": 3,
        },
    ]

    for item in items:
        FAQItem.objects.create(**item)


def reverse_faq(apps, schema_editor):
    FAQItem = apps.get_model("faq", "FAQItem")
    FAQItem.objects.filter(
        question__in=[
            "How do I pay?",
            "What will BirdSoc SG do with the proceeds from merchandise sales?",
            "How do I get my items?",
            "Can I buy the items on site?",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_faq, reverse_faq),
    ]
