# Generated by Django 4.2.15 on 2024-08-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0015_orderlinediscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="collection_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="collection_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
