# Generated by Django 4.2.15 on 2024-08-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0016_order_collection_date_order_collection_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentevent",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
