# Generated by Django 4.2.15 on 2024-08-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0019_paymentevent_verified_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentevent",
            name="verified",
        ),
        migrations.RemoveField(
            model_name="paymentevent",
            name="verified_by",
        ),
    ]
