# Generated by Django 4.2.15 on 2024-08-22 14:14

from django.db import migrations


def create_shipping_event_types(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ShippingEventType = apps.get_model("order", "ShippingEventType")
    db_alias = schema_editor.connection.alias
    ShippingEventType.objects.using(db_alias).bulk_create(
        [
            ShippingEventType(name="collected", code="collected"),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0020_remove_paymentevent_verified_and_more"),
    ]

    operations = [
        migrations.RunPython(create_shipping_event_types),
    ]
