# Generated by Django 4.2.15 on 2024-08-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0021_auto_20240822_2214"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="donation_amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
