# Generated by Django 4.2.15 on 2024-08-18 06:24

from django.db import migrations


def create_payment_event_types(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    PaymentEventType = apps.get_model("order", "PaymentEventType")
    db_alias = schema_editor.connection.alias
    PaymentEventType.objects.using(db_alias).bulk_create(
        [
            PaymentEventType(name="paynow-auto-verified", code="paynow-auto-verified"),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0022_order_donation_amount"),
    ]

    operations = [
        migrations.RunPython(create_payment_event_types),
    ]
