# Generated by Django 4.2.15 on 2026-02-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0024_line_num_allocated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineprice",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_prices",
                to="order.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuschange",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_changes",
                to="order.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="surcharge",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="surcharge",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surcharges",
                to="order.order",
                verbose_name="Order",
            ),
        ),
    ]
