# Generated by Django 4.2.15 on 2026-02-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0025_alter_lineprice_order_alter_orderstatuschange_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["start"],
            },
        ),
    ]
