# Generated by Django 4.2.15 on 2025-02-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0003_auto_20181115_1953"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("email_description", models.TextField(blank=True, null=True)),
                ("email_description_full", models.TextField(blank=True, null=True)),
                ("website_home_description", models.TextField(blank=True, null=True)),
                ("website_faq_description", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
