# Generated by Django 4.2.15 on 2025-02-24 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0004_dynamicshippingmethod"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dynamicshippingmethod",
            name="is_active",
        ),
    ]
