# Generated by Django 4.2.15 on 2025-02-24 14:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0006_migrate_shipping_methods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicshippingmethod",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dynamicshippingmethod",
            name="email_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Email description"
            ),
        ),
        migrations.AlterField(
            model_name="dynamicshippingmethod",
            name="email_description_full",
            field=models.TextField(
                blank=True, null=True, verbose_name="Full email description"
            ),
        ),
        migrations.AlterField(
            model_name="dynamicshippingmethod",
            name="website_faq_description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Website FAQ  description"
            ),
        ),
        migrations.AlterField(
            model_name="dynamicshippingmethod",
            name="website_home_description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Website home description"
            ),
        ),
    ]
