# Generated by Django 4.2.15 on 2025-02-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0007_alter_dynamicshippingmethod_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicshippingmethod",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dynamicshippingmethod",
            name="website_faq_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Website FAQ description"
            ),
        ),
        migrations.AlterField(
            model_name="dynamicshippingmethod",
            name="website_home_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Website home description"
            ),
        ),
    ]
