# Generated by Django 4.2.15 on 2025-03-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0008_alter_dynamicshippingmethod_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicshippingmethod",
            name="available_to_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dynamicshippingmethod",
            name="is_self_collect",
            field=models.BooleanField(default=False),
        ),
    ]
