# Generated by Django 4.2.15 on 2026-04-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BannerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="banners/")),
                (
                    "show_on_product",
                    models.BooleanField(
                        default=False,
                        help_text="Show on the homepage and products page",
                    ),
                ),
                (
                    "show_on_event",
                    models.BooleanField(
                        default=False, help_text="Show on the homepage and events page"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Banner Image",
                "verbose_name_plural": "Banner Images",
                "ordering": ["order", "id"],
            },
        ),
    ]
