# Generated by Django 4.2.15 on 2026-04-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Displayed as a sitewide text banner. HTML is supported."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Text Banner",
                "verbose_name_plural": "Text Banners",
            },
        ),
    ]
