# Generated by Django 4.2.15 on 2024-08-23 12:21

from django.db import migrations


def create_communication_event_types(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    CommunicationEventType = apps.get_model("communication", "CommunicationEventType")
    db_alias = schema_editor.connection.alias
    CommunicationEventType.objects.using(db_alias).bulk_create(
        [
            CommunicationEventType(name="Payment confirmed", code="PAYMENT_CONFIRMED"),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0004_auto_20200801_0817"),
    ]

    operations = [migrations.RunPython(create_communication_event_types)]
