# Generated by Django 4.2.15 on 2024-09-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_auto_20200801_0817"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
