# Generated by Django 4.2.15 on 2024-10-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0008_emailalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailalert",
            name="sent_date",
            field=models.DateField(null=True),
        ),
    ]
