# Generated by Django 4.2.15 on 2024-08-18 02:34

import apps.payment.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_auto_20200801_0817"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="payment_proof",
            field=models.ImageField(
                null=True, upload_to=apps.payment.models.get_payment_proof_path
            ),
        ),
    ]
