# Generated by Django 4.2.15 on 2024-08-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_source_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
