# Generated by Django 4.2.15 on 2024-08-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0008_source_verified_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="source",
            old_name="verified_by",
            new_name="payment_verified_by",
        ),
    ]
