# Generated by Django 4.2.15 on 2024-08-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_rename_verified_by_source_payment_verified_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="payment_verified_on",
            field=models.DateTimeField(null=True),
        ),
    ]
