# Generated by Django 4.2.15 on 2026-04-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0010_source_payment_verified_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reference", models.CharField(db_index=True, max_length=25)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
