# Generated by Django 4.2.15 on 2025-03-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refund", "0002_refundrequest_disbursed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="refundrequest",
            name="refund_number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
