# Generated by Django 4.2.15 on 2024-08-28 13:39

from django.db import migrations
from oscar.apps.offer.custom import create_benefit


def create_benefit_runner(apps, schema_editor):
    from apps.offer.models import Discount20Cap10

    return create_benefit(Discount20Cap10)


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0012_fixedunitdiscountbenefit_alter_benefit_type"),
    ]

    operations = [migrations.RunPython(create_benefit_runner)]
