# Generated by Django 4.2.15 on 2024-09-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0013_auto_20240828_2139"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount20Cap10",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("offer.benefit",),
        ),
    ]
