# Generated by Django 4.2.15 on 2026-02-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0027_attributeoption_code_attributeoptiongroup_code_and_more"),
        ("offer", "0014_discount20cap10"),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="excluded_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products with these categories are excluded from the range when Includes all products is checked",
                related_name="excludes",
                to="catalogue.category",
                verbose_name="Excluded Categories",
            ),
        ),
    ]
